name: Create Release on Windows

on: [push]

jobs:
  build:
    name: Create Release on Windows
    runs-on: windows-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: cache-m2
      name: Cache Maven packages
      uses: actions/cache@v3.0.1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 16
    - id: show-environment
      name: Show environment
      run: |
        # Show environment
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        docker -v
        mvn -v
        cat ~/.m2/settings.xml

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: |
        # Build
        mvn --no-transfer-progress --batch-mode package
        mkdir package
        cp target/photosrenamer-1.4.1-complete.jar package/
        ls -l package/
    - id: jpackage
      name: Package installers
      run: |
        # jpackage
        mkdir installer
        jpackage --verbose "@jpackage.cfg" "@jpackage-windows.cfg"

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: windows-${{ github.sha }}
        release_name: windows-${{ github.sha }}
        draft: false
        prerelease: false
    - id: upload-release
      name: Upload photosrenamer distribution
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./installer/photosrenamer-1.4.1.msi
        asset_name: photosrenamer-1.4.1.msi
        asset_content_type: application/x-binary
