name: Create Release on Windows

on: [push]

jobs:
  build:
    name: Create Release on Windows
    runs-on: windows-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: |
        gradle -v
        gradle build
        jpackage --verbose "@jpackage.cfg" "@jpackage-windows.cfg"

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: windows-${{ github.sha }}
        release_name: windows-${{ github.sha }}
        draft: false
        prerelease: false
    - id: upload-release
      name: Upload photosrenamer distribution
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./build/distributions/photosrenamer-1.4.0.msi
        asset_name: photosrenamer-1.4.0.msi
        asset_content_type: application/x-binary
