name: Quick Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Quick build
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
<<<<<<< Updated upstream
      uses: sualeh/prepare-maven-build@v1.3.5
=======
      uses: sualeh/prepare-maven-build@v1.3.3
>>>>>>> Stashed changes

# BUILD AND TEST
    - id: build-test
      name: Build all modules and run tests
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          package
