name: Create Release

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[A-Z]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.1

# BUILD AND TEST
    - id: build-test
      name: Build all modules and run tests
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          package

# CREATE A RELEASE WITH JRELEASER
    - id: run-jreleaser
      name: Run JReleaser
      uses: jreleaser/release-action@v2
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Persist JReleaser logs
    - id: persist-jreleaser-logs
      name: Persist JReleaser logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jreleaser-release
        path: |
          out/jreleaser/trace.log
          out/jreleaser/output.properties

